CREATE TABLE warehouses (
    id INTEGER NOT NULL AUTOINCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    latitude TEXT NOT NULL,
    longitude TEXT NOT NULL
);

CREATE TABLE items (
    id INTEGER NOT NULL PRIMARY KEY,
    warehouse_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    stock INTEGER NOT NULL
);